name: restaurant_app
description: "A comprehensive Flutter application for discovering restaurants, viewing detailed menus, and managing user reviews. Built by."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  google_fonts: ^8.0.2
  http: ^1.6.0
  lottie: ^3.3.2
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
